_g141210300_ibrahim_topcuoglu_WebPrejesi/FilmSitesi/Areas/Admin/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FilmSitesi.Models;
using FilmSitesi.DAL;
namespace FilmSitesi.Areas.Admin.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin/Admin
        uygulamalarContext db = new uygulamalarContext();
        public ActionResult Index()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Giris", "Panel");
            }

            try
            {
                return View(db.Adminler.ToList());
            }
            catch (Exception)
            {
                ViewBag.Hata = "Admin eklenirken Hatalar Oluştu.";
                return View();
            }

        }
        public ActionResult Ekle()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Giris", "Panel");
            }
            return View();
           
        }
        [HttpPost]
        public ActionResult Ekle(tbl_Admin k)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    int say = db.Adminler.Where(x => x.AdminAdi.ToLower() == k.AdminAdi.ToLower()).Count();
                    if (say == 0)
                    {
                        k.AdminAdi = k.AdminAdi.ToUpper();
                        db.Adminler.Add(k);
                        db.SaveChanges();

                    }
                    else
                    {
                        ModelState.AddModelError("", "böyle bir Admin zaten var.");
                    }
                }
                catch (Exception)
                {
                    ViewBag.Hata = "Admin eklenirken Hatalar Oluştu.";
                }
            }
            return View();
        }
        public ActionResult Sil(int? id)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Giris", "Panel");
            }

            try
            {
                var k = db.Adminler.Find(id);
                return View(k);
            }
            catch (Exception)
            {
                ViewBag.Hata = "Admin Silinirken Hatalar Oluştu.";
                return View();
            }

        }
        [HttpPost]
        public ActionResult Sil( int id )
        {
            try
            {
                var k = db.Adminler.Find(id);
                db.Adminler.Remove(k);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception) { 
         
                ViewBag.Hata = "Admin silinirken Hatalar Oluştu.";
                return View();
            }

        }
        public ActionResult Guncelle(int? id)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Giris", "Panel");
            }

            if (id == null)
                return RedirectToAction("index");
            try
            {
                var k = db.Adminler.Find(id);
                return View(k);
            }
            catch (Exception)
            {

                ViewBag.Hata = "Admin Güncellenirken Hatalar Oluştu.";
                return View();
            }
        }
        [HttpPost]
        public ActionResult Guncelle(tbl_Admin k, int id)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    var m = db.Adminler.Find(id);
                    m.AdminAdi = k.AdminAdi.ToUpper();
                    m.AdminSifre = k.AdminSifre;
                    db.SaveChanges();
                    ViewBag.Mesaj = "Başarıyla Güncellendi";
                    return RedirectToAction("index");

                }
            }
            catch (Exception)
            {
                ViewBag.Hata = "Admin Guncellerken Hatalar Oluştu.";
            }
            return View();
        }
    }
}

_g141210300_ibrahim_topcuoglu_WebPrejesi/FilmSitesi/Areas/Admin/Controllers/FilmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FilmSitesi.Models;
using FilmSitesi.DAL;
using System.IO;
namespace FilmSitesi.Areas.Admin.Controllers
{
    public class FilmController : Controller
    {
        uygulamalarContext db = new uygulamalarContext();
        public ActionResult Index()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Giris", "Panel");
            }

            try
            {
                ViewBag.Film = db.Filmler.OrderBy(x => x.FilmAdi).ToList();
                return View(db.Filmler.ToList());
            }
            catch (Exception)
            {
                ViewBag.Hata = "Hiç film yok";
                return View();
            }
        }
        public ActionResult Ekle()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Giris", "Panel");
            }

            ViewBag.Kategori = db.Kategoriler.OrderBy(x => x.KategoriAdi).ToList();
            return View();
        }
        [HttpPost]
        public ActionResult Ekle(tbl_Film m)
        {
            m.resimUrl = "/assets/img/film/";
            if (ModelState.IsValid)
            {
                try
                {
                    if (Request.Files.Count > 0)
                    {
                        var file = Request.Files[0];

                        if (file != null && file.ContentLength > 0)
                        {
                            string[] uzantilar = { ".JPG", ".JPEG", ".PNG", ".BMP", ".GIF" };
                            Random sayi = new Random();
                            int nameID = sayi.Next(1, 10000); ;

                            for (int i = 0; i < uzantilar.Count(); i++)
                            {
                                if (file.FileName.ToString().ToUpper().EndsWith(uzantilar[i]))
                                {
                                    m.resimUrl += m.FilmAdi + nameID.ToString() + uzantilar[i];
                                    db.Filmler.Add(m);
                                    db.SaveChanges();
                                    var path = Path.Combine(Server.MapPath("~/assets/img/film/"), m.FilmAdi + nameID.ToString() + uzantilar[i]);
                                    file.SaveAs(path);
                                    ViewBag.Mesaj = "Film Başarıyla eklendi.";
                                    return RedirectToAction("index");
                                }
                            }
                        }
                    }
                    return RedirectToAction("index");
                }
                catch (Exception)
                {
                    ViewBag.Hata = "Film eklenirken Hatalar Oluştu.";
                }
            }
            return View();
        }
        [HttpGet]
        public ActionResult Sil(int? id)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Giris", "Panel");
            }

            if (id == null)
                return RedirectToAction("Index");
            try
            {
                var k = db.Filmler.Find(id);
                return View(k);
            }
            catch (Exception)
            {
                ViewBag.Hata = "Film eklenirken Hatalar Oluştu.";
                return View();
            }
        }
        [HttpPost]
        public ActionResult Sil(int id)
        {
            try
            {
                var k = db.Filmler.Find(id);
                db.Filmler.Remove(k);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ViewBag.Hata = "Film silinirken Hatalar Oluştu.";
                return View();
            }
        }

        public ActionResult Guncelle(int? id)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Giris", "Panel");
            }
            try
            {
                ViewBag.Kategori = db.Kategoriler.OrderBy(x => x.KategoriAdi).ToList();
                var k = db.Filmler.Find(id);

                return View(k);
            }
            catch (Exception)
            {

                return RedirectToAction("index");
            }



        }
        [HttpPost]
        public ActionResult Guncelle(tbl_Film k, int id)
        {
            try
            {
               
                var m = db.Filmler.Find(id);
                m.resimUrl = "/assets/img/film/";
                if (Request.Files.Count > 0)
                {
                    var file = Request.Files[0];

                    if (file != null && file.ContentLength > 0)
                    {
                        string[] uzantilar = { ".JPG", ".JPEG", ".PNG", ".BMP", ".GIF" };
                        Random sayi = new Random();
                        int nameID = sayi.Next(1, 10000); ;

                        for (int i = 0; i < uzantilar.Count(); i++)
                        {
                            if (file.FileName.ToString().ToUpper().EndsWith(uzantilar[i]))
                            {
                                m.FilmAdi = k.FilmAdi.ToUpper();
                                m.FilmBilgi = k.FilmBilgi;

                                m.YonetmenAdi = k.YonetmenAdi;
                                m.tbl_KategoriID = k.tbl_KategoriID;
                                m.resimUrl += m.FilmAdi + nameID.ToString() + uzantilar[i];

                                db.SaveChanges();
                                var path = Path.Combine(Server.MapPath("~/assets/img/film/"), m.FilmAdi + nameID.ToString() + uzantilar[i]);
                                file.SaveAs(path);
                                ViewBag.Mesaj = "Film Başarıyla güncellendi.";
                                return RedirectToAction("index");
                            }
                        }
                    }
                }
                return RedirectToAction("index");
            }
            catch (Exception)
            {
                ViewBag.Hata = "Film eklenirken Hatalar Oluştu.";
            }
            return RedirectToAction("index");
        }
    }
}

_g141210300_ibrahim_topcuoglu_WebPrejesi/FilmSitesi/Areas/Admin/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FilmSitesi.Models;
using FilmSitesi.DAL;
namespace FilmSitesi.Areas.Admin.Controllers
{
    public class KategoriController : Controller
    {
        uygulamalarContext db = new uygulamalarContext();
        public ActionResult Index()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Giris", "Panel");
            }

            try
            {
                return View(db.Kategoriler.ToList());
            }
            catch (Exception)
            {
                ViewBag.Hata = "Kategori eklenirken Hatalar Oluştu.";
                return View();
            }
        }
        public ActionResult Ekle()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Giris", "Panel");
            }

            return View();
        }
        [HttpPost]
        public ActionResult Ekle(tbl_Kategori k)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    int say = db.Kategoriler.Where(x => x.KategoriAdi.ToLower() == k.KategoriAdi.ToLower()).Count();
                    if (say == 0)
                    {
                        k.KategoriAdi = k.KategoriAdi.ToUpper();
                        db.Kategoriler.Add(k);
                        db.SaveChanges();
                        ViewBag.Mesaj = "Kategori Eklendi.";
                    }
                    else
                    {
                        ModelState.AddModelError("", "böyle bir kategori zaten var.");
                    }
                }
                catch (Exception)
                {
                    ViewBag.Hata = "Kategori eklenirken Hatalar Oluştu.";
                }
            }
            return View();
        }
        [HttpGet]
        public ActionResult Sil(int? id)
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Giris", "Panel");
            }

            if (id == null)
                return RedirectToAction("Index");
            try
            {
                var k = db.Kategoriler.Find(id);
                return View(k);
            }
            catch (Exception)
            {
                ViewBag.Hata = "Kategori eklenirken Hatalar Oluştu.";
                return View();
            }

        }
        [HttpPost]
        public ActionResult Sil(int id)
        {
            try
            {
                var k = db.Kategoriler.Find(id);
                db.Kategoriler.Remove(k);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ViewBag.Hata = "Kategori silinirken Hatalar Oluştu.";
                return View();
            }
        }
        public ActionResult Guncelle(int? id)
        {
            if (id == null)
                return RedirectToAction("index");
            try
            {
                var k = db.Kategoriler.Find(id);
                return View(k);
            }
            catch (Exception)
            {

                ViewBag.Hata = "Kategori eklenirken Hatalar Oluştu.";
                return View();
            }
        }
        [HttpPost]
        public ActionResult Guncelle(tbl_Kategori k,int id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var m = db.Kategoriler.Find(id);
                    m.KategoriAdi = k.KategoriAdi.ToUpper();
                    db.SaveChanges();
                    return RedirectToAction("index");
                }
            }
            catch (Exception)
            {
                ViewBag.Hata = "Kategori Guncellerken Hatalar Oluştu.";
            }
            return View();
        }
    }
}

_g141210300_ibrahim_topcuoglu_WebPrejesi/FilmSitesi/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>

    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Modern Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Bootstrap Core CSS -->
    <link href="~/Areas/Admin/Content/css/bootstrap.min.css" rel='stylesheet' type='text/css' />
    <!-- Custom CSS -->
    <link href="~/Areas/Admin/Content/css/style.css" rel='stylesheet' type='text/css' />
    <link href="~/Areas/Admin/Content/css/font-awesome.css" rel="stylesheet">
    <!-- jQuery -->
    <script src="~/Areas/Admin/Content/js/jquery.min.js"></script>
    <!----webfonts--->
    <link href='//fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900' rel='stylesheet' type='text/css'>
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="top1 navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                  <span class="sr-only">Toggle navigation</span>
                    
                 <div class="col-md-10">
                    <div style="float:left;"><a class="navbar-brand" href="/Admin/Panel/Index">Admin Paneli</a></div>
                        <div class="col-md-1"></div>
                <div class="col-md-1"> @{Html.RenderAction("AdminName", "Panel");}<a href="/Admin/Panel/Cikis">Çıkış</a></div>
              

                </div>
             
            </div>
                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li>
                                @Html.ActionLink("Anasayfa", "Index", "Panel")
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-indent nav_icon"></i> Kategoriler<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        @Html.ActionLink("Ekle", "Ekle", "Kategori")
                                    </li>
                                    <li>
                                        @Html.ActionLink("Düzenle/Sil", "Index", "Kategori")
                                    </li>
                                </ul>
                            <li>
                                <a href="#"><i class="fa fa-laptop nav_icon"></i>Film<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <ul class="nav nav-second-level">
                                        <li>
                                            @Html.ActionLink("Ekle", "Ekle", "Film")
                                        </li>
                                        <li>
                                            @Html.ActionLink("Düzenle/Sil", "Index", "Film")
                                        </li>
                                    </ul>
                                </ul>

                            <li>
                                <a href="#"><i class="fa fa-laptop nav_icon"></i>Admin<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <ul class="nav nav-second-level">
                                        <li>
                                            @Html.ActionLink("Ekle", "Ekle", "Admin")
                                        </li>
                                        <li>
                                            @Html.ActionLink("Düzenle/Sil", "Index", "Admin")
                                        </li>
                                    </ul>
                                </ul>

                            <li>
                                <a href="#"><i class="fa fa-laptop nav_icon"></i>Bize Ulaş<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level">
                                    <ul class="nav nav-second-level">
                                        <li>
                                            @Html.ActionLink("Oku/Sil", "Bizeulasin", "Panel")
                                        </li>

                                    </ul>
                                </ul>

                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
                <!-- /.navbar-static-side -->
        </nav>
        <div id="page-wrapper">
            <div class="graphs">
                <div class="md">@RenderBody()</div>

            </div><div style="clear:both;" />
            <div class="copy_layout">
                Admin Paneli
            </div>
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- Nav CSS -->
    <link href="~/Areas/Admin/Content/css/custom.css" rel="stylesheet">
    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/Areas/Admin/Content/js/metisMenu.min.js"></script>
    <script src="~/Areas/Admin/Content/js/custom.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Areas/Admin/Content/js/bootstrap.min.js"></script>



</body>
</html>